project_id = "lbxjsemcruizsxglfesw"

[functions.analyze-face]
verify_jwt = false

[functions.hormuud-payment]
verify_jwt = false

[functions.analyze-health]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.waafipay-subscribe]
verify_jwt = false

[functions.ai-health-tips]
verify_jwt = false

[functions.analyze-food]
verify_jwt = false

[functions.analyze-food-by-weight]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.hormuud-evc-payment]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
