project_id = "lbxjsemcruizsxglfesw"

[functions.analyze-face]
verify_jwt = false

[functions.hormuud-payment]
verify_jwt = false

[functions.analyze-health]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.waafipay-subscribe]
verify_jwt = false
