[build]
  publish = "."

[[redirects]]
  from = "/faceglow/*"
  to = "/faceglow/:splat"
  status = 200

[[redirects]]
  from = "/somali-speak-buddy/*"
  to = "/somali-speak-buddy/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
