[build]
  publish = "."

[[redirects]]
  from = "/faceglow/*"
  to = "/faceglow/index.html"
  status = 200

[[redirects]]
  from = "/somali-speak-buddy/*"
  to = "/somali-speak-buddy/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
